#!/bin/bash
# Default programs:
if [[ -x "$(command -v nvim)" ]]
then 
    alias vim="nvim" vimdiff="nvim -d"
    alias vim="nvim"
    alias vi="nvim"
fi

alias v="$EDITOR"
alias e="$EDITOR"
alias oo="xdg-open ."
alias o="xdg-open"
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
alias hdmi="xrandr --output HDMI2 --auto --left-of eDP1"

# https://github.com/jackpot51/dotfiles/blob/master/bash/.bash_aliases
if command -v flatpak > /dev/null
then
    # Get a list of flatpak applications in the reverse domain name format
    readarray -t ids < <(flatpak list --app --columns=application)
    for id in "${ids[@]}"
    do
        # Take everything past the last dot (the name)
        name="${id##*.}"
        # Make it lowercase to approximate binary name
        binary="${name,,}"

        # If there is not already a command at that name
        if ! command -v "${binary}" > /dev/null
        then
            # Create an alias that runs the flatpak
            alias "$binary=flatpak run \"$id\""
        fi
    done
fi
