#!/bin/bash
# Get the aliases and functions
# Use XDG spec for bashrc
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/bashrc" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/shell/bashrc"
fi

# User specific environment and startup programs

# Default programs:
if [[ -x "$(command -v nvim)" ]]
then 
    export EDITOR="nvim"
else
    export EDITOR="vi"
fi

export BROWSER="brave"
export TERMINAL="alacritty"
export MANPAGER='nvim +Man!'

# Clean up ~/
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export LESSHISTFILE="-"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
# Ruby: Use XDG specification
export GEM_HOME="$XDG_DATA_HOME"/gem
export GEM_SPEC_CACHE="$XDG_CACHE_HOME"/gem
export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME"/bundle 
export BUNDLE_USER_CACHE='"$XDG_CACHE_HOME"/bundle'
export BUNDLE_USER_PLUGIN='"$XDG_DATA_HOME"/bundle'

# Other program settings:
export MOZ_USE_XINPUT2="1"		# Mozilla smooth scrolling/touchpads.

# Autostart i3 or Gnome (Wayland)
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
    exec startx
fi
if [[ -z $DISPLAY && $(tty) == /dev/tty2 && $XDG_SESSION_TYPE == tty ]]; then
  MOZ_ENABLE_WAYLAND=1 QT_QPA_PLATFORM=wayland XDG_SESSION_TYPE=wayland exec dbus-run-session gnome-session
fi
if [[ -z $DISPLAY && $(tty) == /dev/tty3 && $XDG_SESSION_TYPE == tty ]]; then
    exec tmux
fi
